- .gitignore
- .travis.yml
- Makefile
- README.md
- go.mod
- main.go
> Switch to Go modules

- secrets_controller.go
Adds support for the Python AWS SDK (boto3) by supporting getting
credentials from an external process.
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes
The external process is `cat /meta/aws-iam/credentials.json`.
> Add support for Python AWS SDK

- credentials_getter_test.go
- go.mod
- go.sum
- main.go
- pod_watcher.go
- pod_watcher_test.go
- role_store.go
- role_store_test.go
- secrets_controller.go
- secrets_controller_test.go
Add unit tests and fix bugs in role store.
> Unit tests

- .travis.yml
- Dockerfile
- README.md
> Add coverage report

- README.md
- docs/sdk-configuration.md
Document per SDK configuration
> Document per SDK configuration

- README.md
- scripts/get_credentials.sh
Update the bootstrap guide to use Process
> Update the bootstrap guide to use Process

- docs/sdk-configuration.md
- go.mod
- go.sum
Update SDK and document NewSession
> Update SDK and document NewSession

- .travis.yml
> Update go version in travis

- go.mod
- go.sum
- hack/update-codegen.sh
- pkg/client/clientset/versioned/clientset.go
- pkg/client/clientset/versioned/fake/clientset_generated.go
Update code generation to be more robust
> Update code generation to be more robust

- credentials_getter.go
- credentials_getter_test.go
> Fix handling of roles with paths

- .golangci.yml
> Add golangci checks

- README.md
Remove the **Proof of Concept** text as this is no longer the case. It's the real deal :)
> No longer a Proof of Concept

- README.md
Mention kiam along side kube2iam to reference prio art/alternatives in README.
> Link to kiam in README

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- MAINTAINERS
- SECURITY.md
Add required project assets for Zalando SE OSS
> Add required project assets for Zalando SE OSS

- Makefile
- README.md
- awsiamrole_controller.go
- awsiamrole_controller_test.go
- delivery.yaml
- docs/deployment.yaml
- docs/deployment_with_role.yaml
- go.mod
- hack/update-codegen.sh
- main.go
- pkg/apis/zalando.org/v1/register.go
- pkg/client/clientset/versioned/clientset.go
- pkg/client/clientset/versioned/fake/clientset_generated.go
- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
- pkg/client/clientset/versioned/typed/zalando.org/v1/awsiamrole.go
- pkg/client/clientset/versioned/typed/zalando.org/v1/fake/fake_awsiamrole.go
- pkg/client/clientset/versioned/typed/zalando.org/v1/fake/fake_zalando.org_client.go
- pkg/client/clientset/versioned/typed/zalando.org/v1/zalando.org_client.go
- pkg/client/informers/externalversions/factory.go
- pkg/client/informers/externalversions/generic.go
- pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
- pkg/client/informers/externalversions/zalando.org/interface.go
- pkg/client/informers/externalversions/zalando.org/v1/awsiamrole.go
- pkg/client/informers/externalversions/zalando.org/v1/interface.go
- pkg/client/listers/zalando.org/v1/awsiamrole.go
- pkg/clientset/unified.go
* Rename imports to new repo location
* Add `delivery.yaml` to build on CDP.
> Rename imports to new repo location

- docs/deployment.yaml
> Fixed Memory Suffix in deployment.yaml

- awsiamrole_controller.go
Fix spelling of the world credential
> fix spelling of the word credentials

- .travis.yml
- go.mod
- go.sum
Update for building with go 1.13
> Update for building with go 1.13

- awsiamrole_controller.go
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
> fix typo in error log

- docs/aws_iam_role_crd.yaml
> move away from deprecated apiVersion for CRD

- delivery.yaml
(or how to trigger the CI again)
> Some small change to the pipeline step name

- Dockerfile
- Makefile
> Use static base image

- secrets_controller.go
Fixes crash in the healthReporter logic introduced in: #60
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11dcc6c]
goroutine 1 [running]:
main.(*SecretsController).Run(0x400009c4e0, {0x1c176f0, 0x4000660280})
/workspace/secrets_controller.go:122 +0x8c
main.main()
/workspace/main.go:121 +0x12bc
```
> Fix healthReporter
